### ISSUE TITLE
Cannot find module 'ignore-walk'

### ISSUE THREAD

**Issue by camlafit** [pucelle/vscode-css-navigation#52]
Hello

My vscodium configuration :
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-12T00:32:13.710Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.19.0-14-amd64

I get this following error. I can do some test if needed.
Thanks a lot 

````
[17:54:27] Client for workspace folder "personal" started
internal/modules/cjs/loader.js:975
  throw err;
  ^

Error: Cannot find module 'ignore-walk'
Require stack:
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file-tracker.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/index.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-range-parser.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-service.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/html-service.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/index.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/server.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file-tracker.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/index.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-range-parser.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-service.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/html-service.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/index.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/server.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js'
  ]
}
[Info  - 17:54:30] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:975
  throw err;
  ^

Error: Cannot find module 'ignore-walk'
Require stack:
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file-tracker.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/index.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-range-parser.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-service.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/html-service.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/index.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/server.js
- /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/file-tracker.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/helpers/index.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-range-parser.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/css/css-service.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/html-service.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/languages/html/index.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/server/out/server.js',
    '/home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js'
  ]
}
```

**Comment by camlafit** [comment]
Hello

A workaround looks be :
```
cd /home/user/.vscode-oss/extensions/pucelle.vscode-css-navigation-1.10.3
npm install ignore-walk 
```

**Comment by pucelle** [comment]
Sorry, I fork the module `ignore-walk` and publish it as private npm package, but didn't changes it's reference path...

**Comment by pucelle** [comment]
Already fixed.

**Comment by camlafit** [comment]
thanks :)

**Comment by camlafit** [comment]
I do localy patch and looks working. Wait new release to update correctly :)
